#!/bin/sh

#uci set luci.main.mediaurlbase='/luci-static/argon'
#uci commit luci

#timezone
uci set system.@system[0].timezone='CST-8'
uci set system.@system[0].zonename='Asia/Shanghai'
uci commit system
#ssrp
sed -i 's/local ucic = uci.cursor()/local ucic = luci.model.uci.cursor()/g' /usr/share/shadowsocksr/subscribe.lua
sed -i "s/'cbid.shadowsocksr.'/'widget.cbid.shadowsocksr.'/g" /usr/lib/lua/luci/view/shadowsocksr/ssrurl.htm
#feed
sed -i '/openwrt_luci/ { s/snapshots\/packages/releases\/packages-19.07/g; }'      /etc/opkg/distfeeds.conf
sed -i '/openwrt_packages/ { s/snapshots\/packages/releases\/packages-19.07/g; }'  /etc/opkg/distfeeds.conf
sed -i '/openwrt_routing/ { s/snapshots\/packages/releases\/packages-19.07/g; }'   /etc/opkg/distfeeds.conf
sed -i '/openwrt_telephony/ { s/snapshots\/packages/releases\/packages-19.07/g; }' /etc/opkg/distfeeds.conf
sed -i '/natelol/d'                                                                /etc/opkg/distfeeds.conf
sed -i 's,downloads.openwrt.org,mirrors.cloud.tencent.com/lede,g'                  /etc/opkg/distfeeds.conf
#uhttpd
uci set uhttpd.main.rfc1918_filter='0'
uci set uhttpd.main.redirect_https='0'
uci commit uhttpd
/etc/init.d/uhttpd restart
#network
uci set network.globals.packet_steering='1'
uci commit network
#firewall
uci set firewall.@zone[1].fullcone='1'
uci commit firewall
#dropbear
uci set dropbear.@dropbear[0].Interface='lan'
uci commit dropbear
/etc/init.d/dropbear restart
#upnp
uci set upnpd.config.igdv1='1'
uci set upnpd.config.enabled='1'
uci del upnpd.config.enable_upnp
uci del upnpd.config.enable_natpmp
uci set upnpd.config.external_iface='wan'
uci commit upnpd
/etc/init.d/miniupnpd restart
#dnsmasq
sed -i '/log-facility/d' /etc/dnsmasq.conf
echo 'log-facility=/dev/null' >> /etc/dnsmasq.conf
/etc/init.d/dnsmasq restart
#luci cache
rm -rf /tmp/luci-modulecache/
rm -f /tmp/luci-indexcache
#symlink for ip command
ln -sf /sbin/ip /usr/bin/ip
#opkg hold patched packages
opkg flag hold luci-app-ddns
opkg flag hold luci-i18n-ddns-zh-cn
opkg flag hold ddns-scripts
#opkg flag hold ddns-scripts_cloudflare.com-v4
opkg flag hold luci-app-firewall
opkg flag hold firewall
opkg flag hold dnsmasq-full
#free memory
sync ; sync ; sync ; echo 3 > /proc/sys/vm/drop_caches
exit 0
